
services:
    label: 添加service
    view:
        list: $/wpjscc/js/models/service/relation_columns.yaml
        toolbarButtons: link|unlink
jss:
    label: 添加js
    view:
        list: $/wpjscc/js/models/js/relation_columns.yaml
        toolbarButtons: link|unlink
    pivot:
        form:
            fields:
                pivot[is_preload]:
                    label: is_preload
                    type: switch
                    span: auto
                    comment: 是否预先加载
csss:
    label: 添加css
    view:
        list: $/wpjscc/js/models/css/columns.yaml
        toolbarButtons: link|unlink
  